services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    volumes:
      - redis_data:/data

  htemplx:
    container_name: htemplx
    image: htemplx
    environment:
      - DB_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - REDIS_URL=redis:6379
    command: serve
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  redis_data:
