services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379" 
    volumes:
      - redisdata:/data

  htemplx:
    container_name: htemplx
    image: htemplx
    environment:
      - DB_URL=${DB_URL}
      - REDIS_URL=redis:6379
    command: /app/bin/htemplx serve
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    

volumes:
  pgdata:
  redisdata:
